[subs]
  [subs.log]
    onEventsExcept = ["host.touch", "port.touch"]
    doBuiltin = "log"
  [subs.example]
    disabled = true
    onEvents = ["host.new"]
    doShell = "echo Hello {{.Host.IPv4}} - $(date)"
