[triggers]
  [triggers.log]
    onEventsExcept = ["host.touch", "port.touch"]
    doBuiltin = "log"
  [triggeres.example]
    disabled = true
    onEvents = ["host.new"]
    doShell = "echo Hello {{.Host.IPv4}} - $(date)"
  [triggers.gmail]
    disabled = true
    onEvents = ["host.new"]
    doShell = "notify -s 'New host {{.Host.MAC}} on {{.Host.IPv4}}'"
