[triggers]
  [triggers.debug]
    onAny = true
    doShell = "echo '{{.Description}}'"
  [triggers.log]
    onEventsExcept = ["host.touch", "port.touch"]
    doBuiltin = "log"
  [triggeres.example]
    disabled = true
    onEvents = ["host.new"]
    doShell = "echo Hello {{.Host.IPv4}} - $(date)"
  [triggers.gmail]
    disabled = true
    onEvents = ["host.new"]
    doShell = "notify -s 'New host {{.Host.MAC}} on {{.Host.IPv4}}'"
  [triggers.gmail-ssh]
    disabled = true
    onShell = '[ "{{.Host.IPv4}} {{.PortString}}" = "$HOST1 $HOST1_PORT1" ]'
    doShell = "echo '{{.Description}}'"
